files/initialize.sh, files/playbooks/awx.yml
=> Make ceph init optional

files/run.sh
=> Add AWX_ADMIN_MAILADDRESS

Dockerfile.all-in-one, Dockerfile.openstack
=> Add inventory

Dockerfile.all-in-one, Dockerfile.openstack, files/initialize.sh
=> awx: split bootstrap playbook

.github/workflows/build-docker-image-all-in-one.yml, .github/workflows/build-docker-image-openstack.yml
=> github: rebuild the image every hour (8 - 22)

Dockerfile.all-in-one, Dockerfile.openstack
=> Add missing playbooks

Dockerfile.all-in-one, Dockerfile.openstack
=> Copy workflows from osism-ansible

.github/workflows/build-docker-image-all-in-one.yml
=> github: enable luminous build

Dockerfile.all-in-one, Dockerfile.openstack
=> Do not copy tests and validations directory

.github/workflows/build-docker-image-all-in-one.yml
Signed-off-by: Christian Berendt <berendt@23technologies.cloud>
=> Add ceph octopus

Dockerfile.all-in-one, Dockerfile.openstack, files/requirements.txt
=> Use ara 1.5.5

Dockerfile.all-in-one, Dockerfile.openstack
=> Install ansible

Dockerfile.all-in-one, Dockerfile.openstack, files/initialize.sh
=> Use python 3.8

files/initialize.sh
=> Cleanup initialize.sh

.github/workflows/build-docker-image.yml, .github/workflows/check-docker-syntax.yml, README.md, scripts/build.sh
=> Rename repository & use Containerfile

Containerfile
=> Remove virtual environments

.github/workflows/build-docker-image.yml
=> github: add workflow_dispatch to build-docker-image workflow

Containerfile
=> Use awxkit 19.0.0

Containerfile
=> Install supervisor

files/initialize.sh
=> Set ansible_python_interpreter=/usr/bin/python3 in initialize script

files/run.sh
=> Preload data

Containerfile, files/receptor.conf, files/run.sh, files/supervisor.conf
=> Add receptor service

files/initialize.sh, files/run.sh, files/supervisor.conf
=> Fix some nits

Containerfile, files/supervisor.conf
=> Fix supervisor commands

Containerfile
=> Install ansible-runner

.github/workflows/build-docker-image.yml, Containerfile, files/requirements.txt, scripts/build.sh
=> Prepare for execution environments

Containerfile
=> Add missing -p

Containerfile
=> Re-add initialize.sh

Containerfile, files/initialize.sh
=> Wait for AWX before starting the initialization

files/receptor.conf
=> Improve receptor configuration

files/initialize.sh
=> Fix initialize.sh script

.github/workflows/build-docker-image.yml, Containerfile, files/run.sh, files/supervisor.conf, files/update.sh
=> Use awx 19.1.0 & fix some nits

files/requirements.txt
=> Install receptorctl

files/receptor.conf
=> Sync receptor.conf with awx-operator

scripts/build.sh
Signed-off-by: Tim Beermann <beermann@osism.tech>
=> Company name changed
